name = "TWDA v5"
license = "MIT"
licenselink = "https://github.com/username/twda_v5/blob/main/LICENSE"
description = "現代化 Hugo 主題，整合 TailwindCSS v4 + DaisyUI v5 + Alpine.js v3"
homepage = "https://github.com/username/twda_v5"
demosite = "https://twda-v5-demo.netlify.app"
tags = ["responsive", "dark-mode", "tailwindcss", "daisyui", "alpine", "blog", "portfolio"]
features = ["響應式設計", "深色模式", "SEO優化", "快速載入", "現代化組件"]
min_version = "0.147.9"

[author]
  name = "開發者"
  homepage = "https://github.com/username"

[original]
  name = "TWDA v5"
  homepage = "https://github.com/username/twda_v5"
  repo = "https://github.com/username/twda_v5"
