# 主菜單
[[main]]
  name = "首頁"
  url = "/"
  weight = 10

[[main]]
  name = "關於"
  url = "/about/"
  weight = 20

[[main]]
  name = "文章"
  url = "/blogs/"
  weight = 30

[[main]]
  name = "專案"
  url = "/projects/"
  weight = 40

[[main]]
  name = "聯絡"
  url = "/contact/"
  weight = 50

# 頁尾菜單
[[footer]]
  name = "隱私政策"
  url = "/privacy/"
  weight = 10

[[footer]]
  name = "條款與條件"
  url = "/terms/"
  weight = 20

[[footer]]
  name = "聯絡我們"
  url = "/contact/"
  weight = 30
